function graficarError(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 01-May-2017 00:08:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create plot

% Create title
title({'Costo sistema 1'});

% Create xlabel
xlabel({'Métodos'});

% Create ylabel
ylabel({'Tiempo (segundo)'});
Labels = {'Gauss-Jacobi', 'Gauss-Seidel', 'Doolittle', 'Cholesky','QR'};
plot(Y1,'-ob','MarkerSize',5,'MarkerFaceColor','b');
set(gca, 'XTick', 1:5, 'XTickLabel', Labels);

