function graficarValoresIt(vj, vs)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 21-Mar-2017 12:39:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

surf(vj);
surf(vs);
title('Aproximaciones en el sistema 2');
zlabel('Aproximaciones') % y-axis label
xlabel('Iteraciones') % x-axis label
ylabel('Variables');
legend('Gauss-Jacobi', 'Gauss-Seidel');
end