function graficarErrores(vj, vs)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 21-Mar-2017 12:39:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

plot([vj],'-sg','MarkerSize',2,'MarkerFaceColor','g'); hold on;
plot([vs],'-or','MarkerSize',2,'MarkerFaceColor','r'); hold on;

title('Errores en el sistema 2')
xlabel('Iteraciones') % x-axis label
ylabel('Errores');
legend('Gauss-Jacobi', 'Gauss-Seidel');
end