function graficarValores(vd, vc, vqr)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 21-Mar-2017 12:39:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

plot([vd],'-sg','MarkerSize',2,'MarkerFaceColor','g'), hold on;
plot([vc],'-oy','MarkerSize',2,'MarkerFaceColor','r'),
plot([vqr],'-*b','MarkerSize',2,'MarkerFaceColor','b'),hold off;
title('Aproximaciones en el sistema 2')
ylabel('Aproximaciones') % y-axis label
xlabel('Variables') % x-axis label
legend('Doolittle', 'Cholesky', 'QR');
end